// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenCacao.CacaoBeacon;

namespace migratesqlite.Migrations
{
    [DbContext(typeof(CBStorageSQLite.CBContext))]
    partial class CBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("OpenCacao.CacaoBeacon.ExportRotatingProximityIdentifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RPI")
                        .HasMaxLength(16)
                        .HasColumnType("BLOB");

                    b.Property<int>("RollingStartIntervalNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("RpiDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("TEK")
                        .HasMaxLength(16)
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("EXRPI");
                });

            modelBuilder.Entity("OpenCacao.CacaoBeacon.RotatingProximityIdentifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Key")
                        .HasMaxLength(16)
                        .HasColumnType("BLOB");

                    b.Property<ulong>("MAC")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Metadata")
                        .HasMaxLength(4)
                        .HasColumnType("BLOB");

                    b.Property<short>("RssiMax")
                        .HasColumnType("INTEGER");

                    b.Property<short>("RssiMin")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RPI");
                });

            modelBuilder.Entity("OpenCacao.CacaoBeacon.TemporaryExposureKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Key")
                        .HasMaxLength(16)
                        .HasColumnType("BLOB");

                    b.Property<int>("RollingPeriod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RollingStartIntervalNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransmissionRiskLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TEK");
                });
#pragma warning restore 612, 618
        }
    }
}
